services:
  zabbix-server:
    container_name: "zabbix-server"
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    restart: always
    ports:
      - "10051:10051"
    networks:
      - zabbix-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      DB_SERVER_HOST: "zabbix-db"
      DB_PORT: 5432
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix123"
      POSTGRES_DB: "zabbix_db"

  zabbix-web:
    container_name: "zabbix-web"
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - zabbix-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./cert/:/usr/share/zabbix/conf/certs/:ro
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      DB_SERVER_HOST: "zabbix-db"
      DB_PORT: 5432
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix123"
      POSTGRES_DB: "zabbix_db"
      ZBX_MEMORYLIMIT: "1024M"
    depends_on:
      - zabbix-server

  zabbix-agent:
    container_name: "zabbix-agent"
    image: zabbix/zabbix-agent:alpine-7.0-latest
    restart: always
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "zabbix-agent"
      ZBX_SERVER_HOST: "zabbix-server"
    ports:
      - "10050:10050"
      - "31999:31999"
    networks:
      - zabbix-network

  zabbix-db:
    container_name: "zabbix-db"
    image: postgres:16-bullseye
    restart: always
    volumes:
      - zbx_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zabbix-network
    environment:
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix123"
      POSTGRES_DB: "zabbix_db"

networks:
  zabbix-network:
    driver: bridge

volumes:
  zbx_db:
    driver: local
